### ISSUE TITLE
TensorRT Conversion

### ISSUE THREAD

**Issue by alprnbg** [tusharsangam/TransVisDrone#14]
Hello,

I am having some difficulty converting the pretrained weights to tensorrt engine and my guess is that 8gb GPU memory of the jetson orin nano board is not enough. In the paper, I saw that you tested 640 reso model on jetson. Could you please share the weights of that model as well? In the drive I could only find the 1280 reso models.

Thank you very much.

**Comment by tusharsangam** [comment]
Hi, @alprnbg can you provide me a drive link to drop the weights ? currently my drive is full. Sorry for that.

**Comment by alprnbg** [comment]
Thank you very much for the answer Tushar. My colleague reached out to you a couple of days ago via e-mail and you sent the the weights to him already. Thanks :) I am closing the issue.
